name: Tests

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        php: [ 8.1, 8.2 ]

    name: PHP ${{ matrix.php }}

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: json
          coverage: none

      - name: Install the dependencies
        run: |
          composer update --no-progress --prefer-dist --no-interaction

      - name: Execute the tests
        run: composer test
